config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/sap', as: 'rails_admin'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'


  root 'static#home'
  get 'static/scoreboard'
  get 'static/error'
  get 'static/victory'

  resources :users, only: [:edit, :update]
end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	enum role: [
				:victor,
				:player
               ]

	class << self
		$found_or_created=0

		def create_with_omniauth(auth)
			uid=auth.uid
			info=auth.info.symbolize_keys!
			if User.exists?(uid: uid)
				user=User.find_by(uid: uid)
				$found_or_created=1
			else
				user=User.create(uid: uid)
				user.name=info.name
				user.provider=auth.provider
				user.image_url=info.image
				user.role=1
				$found_or_created=2
			end
			user.save!
			user
		end

		def f_o_c
		    return $found_or_created
		end

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_score
    if current_user
  	  @current_score = current_user.score
    end
  end

  def questions
	@questions ||= Question.all
  end

  helper_method :current_user
  helper_method :current_score
  helper_method :questions
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
def create
  auth=request.env["omniauth.auth"]
  user=User.create_with_omniauth(auth)
  reset_session
  session[:user_id]=user.id
  val=User.f_o_c
  if val==1
  	flash[:notice]="Welcome Again!!"
  	redirect_to root_path
  else
  	flash[:notice]="Please Complete Your Profile"
  	redirect_to edit_user_path(id: user.id)
  end
end


def destroy
	reset_session
	flash[:notice]="You have successfully logged Out!!"
	redirect_to root_path
end

def failure
redirect_to root_url, :alert => "Authentication error"
end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    if current_user && current_user.player?
    @my_id=(current_score/10)+1
  	    @question=questions.find(@my_id)
  	    if params[:answer].present?
  	  	  if params[:answer].casecmp(@question.answer)==0
  	  		  flash[:sucess]="Correct!!"
  	  		  current_user.score+=10
              if current_score==100
                 current_user.role=0
              end
  	  		  current_user.save!
              if current_score!=100
  	 	           @my_id=(current_score/10)+1
  	  		       @question=Question.find(@my_id)
  	  	      else
  	  	         redirect_to static_victory_path
  	  	      end
   	  	  end
	      end
    elsif current_user && current_user.victor?
        redirect_to static_victory_path
    end
	end


  def scoreboard
  	@users=User.order(updated_at: :desc)
  	@users=@users.sort_by(&:score).reverse
  end

  def error
  end

  def victory
  	if current_score!=100
  		redirect_to static_error_path
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def edit
	if User.exists?(id: params[:id])
	  @user=User.find(params[:id])
	end

	if @user!=current_user
		redirect_to static_error_path
	end
end

def update
	@user=User.find(params[:id])
	if @user.update(user_params)
		flash[:notice]="Your Profile was successfully Updated!!"
		redirect_to root_path
	else
		flash[:notice]="Sorry!! Could not save!"
		render 'edit'
	end
end

private

def user_params
  params.require(:user).permit(:dob, :name,:college)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TH</title>
  		<meta name="description" content="Learn how to code your first responsive website with the new Twitter Bootstrap 3.">

		<!-- Mobile viewport optimized -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #ecf0f1;">




<div class="navbar navbar-default" id="mera">
<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
 <ul class="nav navbar-nav">

<% if current_user %>

  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
  <li><%= link_to "Scoreboard", static_scoreboard_path %></li>
  <%= link_to "Log Out", signout_path, class: "btn btn-default navbar-btn" %>

<% else %>
  <%= link_to "Facebook", '/auth/facebook', class: "btn btn-default navbar-btn" %>
<% end %>

</ul>
</div>
</div>
<div class="container" id="main">
<%= yield %>
</div>

<br><br><br>
<!-- <footer id="neeche">
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
			<h6>Copyright &copy; 2013 {alchemist95}</h6>
			</div>
-
			<div class="col-sm-4">
				<h6>About Us</h6>
				<p>sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!</p>
			</div>

			<div class="col-sm-2">
				<h6>Navigation</h6>
				<ul class="unstyled">
					<li><a href="#">Home</a></li>
					<li><a href="#">Services</a></li>
					<li><a href="#">Links</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>

			<div class="col-sm-2">
				<h6>Follow Us</h6>
				<ul class="unstyled">
					<li><a href="#">Twitter</a></li>
					<li><a href="#">Facebook</a></li>
					<li><a href="#">Google Plus</a></li>
				</ul>
			</div>

			<div class="col-sm-2">
				<h6>Coded with <span class="glyphicon glyphicon-heart"></span> by alchemist95</h6>
			</div>					</div>
	</div>

</footer> -->


</body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
<br/>
<div class="container">
	<div class="row">
	<div class="col-md-3">
	</div>
	<div class="col-md-6">

	<div class="panel panel-warning">
    	<div class="panel-heading"><h3 style="text-align: center">Edit Your Profile
 	<span style="float:right"><div class="btn-group"><%= link_to "Back", root_path, class:"btn btn-primary" %><%= f.submit "Update", class: 'btn btn-success' %></span></div></h3>
 	</div>
        <div class="panel-body">
        	<div class="form-group">
        	<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			</div>
<br />

            <div class="form-group">
            <%= f.label :score %><br />
            <%= @user.score%>
            </div>
            <div class="form-group">
                <%= f.label :dob%>
                <div class='input-group date' id='datetimepicker1'>
                   <%= f.text_field :dob, class: "form-control"%>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
<br />
            <div class="form-group">
            <%=f.label :college %>
            <%= f.select :college, options_for_select(College.all.collect {|c| c.name.titleize }),{}, class: 'form-control' %>
            </div>
<br />
        </div>
 	</div>
 	</div>

<div class="col-md-3">
	</div>


</div>
</div>

  <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker(
{	format: 'DD/MM/YYYY'}
                	);
            });
        </script>



<% end %>